apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: project2-pv2-raphaelasilva
spec:
  storageClassName: default-storage-class-raphaelasilva
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      namespace: raphaelasilva